### ISSUE TITLE
My coffee is too hot

### ISSUE THREAD

**Issue by austinmeier** [Planteome/demo-planteome-repository#4]
I need coffee, but it's too hot to drink

**Comment by cmungall** [comment]
What temperature would you like sir?

**Comment by cmungall** [comment]
Tough luck

**Comment by leova** [comment]
Read the manual

**Comment by austinmeier** [comment]
standard 185 degrees, please

**Comment by cmungall** [comment]
Did this work for you? @austinmeier @aafolabi
